### ISSUE TITLE
code and result

### ISSUE THREAD

**Issue by rubbishpeople** [lktidaohuoxing/SuperEdge#1]

**Comment by rubbishpeople** [comment]
Thanks for your excellent work. Could you please provide source code or  the test image results for BSDS? I couldn't find them in this project

**Comment by lktidaohuoxing** [comment]
I have finished organizing the code, but because the paper was not accepted and I am too busy recently, I have not uploaded it to GitHub. My email address is playtomarslk@gmail.com. If you are Chinese, please contact my WeChat, 17660439531. I will send you the code and the trained model.
